### ISSUE TITLE
Ability to hide keybinds that are not set

### ISSUE THREAD

**Issue by tikeyike** [kuldarvakker/keybinds-overlay#1]
Feature Request:

Have the ability to hide icons in the overlay that do not have a keybind set.

![image](https://user-images.githubusercontent.com/37505521/111028052-36648080-8448-11eb-8245-044dd186c5b3.png)

Additionally, it would be nice if the order of the icons in the overlay could be rearranged to the users' preference e.g. prayer icon first, then quest icon second, inventory icon third etc.

**Comment by kuldarvakker** [comment]
Thank you for your feature request. As the features you mentioned are in my TODO list, you can be sure that the following features will be added to the plugin soon. 
1. Hide icons that do not have a keybind
2. User's preferences of the layout

**Comment by kuldarvakker** [comment]
The features are now in the source. Waiting for the plugin approval.
